/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

import Models.Proceso;
import Global.Parametros;
import Helpers.Validator;
import javax.swing.JOptionPane;

/**
 *
 * @author Lucas
 */
public class Opcion1 extends javax.swing.JFrame {
    boolean Pasa=false;
    /**
     * Creates new form Opcion1
     */
    public Opcion1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Menú = new javax.swing.JLabel();
        BOTONVOLVER = new javax.swing.JButton();
        botonAgregarTiempoES = new javax.swing.JButton();
        botonAgregarQuantum = new javax.swing.JButton();
        botonAgregarProceso = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Menú.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        Menú.setText("        ESTABLECIENDO PARAMETROS");
        jPanel1.add(Menú, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 540, 120));

        BOTONVOLVER.setBackground(new java.awt.Color(204, 204, 204));
        BOTONVOLVER.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        BOTONVOLVER.setText("Volver");
        BOTONVOLVER.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BOTONVOLVERMouseClicked(evt);
            }
        });
        BOTONVOLVER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTONVOLVERActionPerformed(evt);
            }
        });
        jPanel1.add(BOTONVOLVER, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 590, 160, 60));

        botonAgregarTiempoES.setBackground(new java.awt.Color(0, 0, 0));
        botonAgregarTiempoES.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        botonAgregarTiempoES.setForeground(new java.awt.Color(255, 255, 255));
        botonAgregarTiempoES.setText("AGREGAR");
        botonAgregarTiempoES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarTiempoESActionPerformed(evt);
            }
        });
        jPanel1.add(botonAgregarTiempoES, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 110, 50));

        botonAgregarQuantum.setBackground(new java.awt.Color(0, 0, 0));
        botonAgregarQuantum.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        botonAgregarQuantum.setForeground(new java.awt.Color(255, 255, 255));
        botonAgregarQuantum.setText("AGREGAR");
        botonAgregarQuantum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarQuantumActionPerformed(evt);
            }
        });
        jPanel1.add(botonAgregarQuantum, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 220, 110, 50));

        botonAgregarProceso.setBackground(new java.awt.Color(0, 0, 0));
        botonAgregarProceso.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        botonAgregarProceso.setForeground(new java.awt.Color(255, 255, 255));
        botonAgregarProceso.setText("AGREGAR");
        botonAgregarProceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarProcesoActionPerformed(evt);
            }
        });
        jPanel1.add(botonAgregarProceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, 110, 50));

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel2.setText("EL TIEMPO DE RUTINA DEL SISTEMA OPERATIVO ESTÁ PREDETERMINADO EN 10 Ut");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 520, 710, 40));

        jLabel3.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel3.setText("CANTIDAD DE PROCESOS");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, 260, 60));

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel1.setText("INGRESE EL TIEMPO DE ENTRADA/SALIDA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 370, 60));

        jLabel4.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel4.setText("INGRESE EL VALOR DEL QUANTUM");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 170, 290, 40));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/650043d8d746e5e29efde3534c60f823.jpg"))); // NOI18N
        Fondo.setText("jLabel1");
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 670));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BOTONVOLVERMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BOTONVOLVERMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_BOTONVOLVERMouseClicked

    private void BOTONVOLVERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTONVOLVERActionPerformed
        // TODO add your handling code here:
        DataFrame abrir=new DataFrame();
        abrir.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_BOTONVOLVERActionPerformed

    private void botonAgregarProcesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarProcesoActionPerformed
        // TODO add your handling code here:
        Parametros.cantidadDeProcesos=Validator.Validate(Parametros.cantidadDeProcesos);
    }//GEN-LAST:event_botonAgregarProcesoActionPerformed

    private void botonAgregarQuantumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarQuantumActionPerformed
        // TODO add your handling code here:
          Parametros.quantum=Validator.Validate(Parametros.quantum);
    }//GEN-LAST:event_botonAgregarQuantumActionPerformed

    private void botonAgregarTiempoESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarTiempoESActionPerformed
        // TODO add your handling code here:
        Parametros.tiempoDeEntradaSalida=Validator.Validate(Parametros.tiempoDeEntradaSalida);
    }//GEN-LAST:event_botonAgregarTiempoESActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Opcion1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Opcion1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Opcion1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Opcion1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Opcion1().setVisible(true);
            }
        });
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BOTONVOLVER;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Menú;
    private javax.swing.JButton botonAgregarProceso;
    private javax.swing.JButton botonAgregarQuantum;
    private javax.swing.JButton botonAgregarTiempoES;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
